services:
  postgresql:
    container_name: temporal_db
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:14
    ports:
      - "5432:5432"
    networks:
      - net

  temporal:
    image: temporalio/auto-setup:1.23
    container_name: temporal
    hostname: temporal
    depends_on:
      postgresql:
        condition: service_started
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development-sql.yaml
      - TEMPORAL_ADDRESS=temporal:7233
      - LOG_LEVEL=error
    ports:
      - "7233:7233"
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    labels:
      kompose.volume.type: configMap
    networks:
      - net

  temporal_ui:
    container_name: temporal_ui
    depends_on:
      temporal:
        condition: service_started
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - LOG_LEVEL=error
    image: temporalio/ui:2.30.2
    networks:
      - net
    ports:
      - "8080:8080"

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
